out_dir: /home/andrew/Desktop/fishsim-smk

codebook_file: config/codebook.tsv
data_org_file: config/data_org.tsv
run_config_dir: config/runs
runs:
  - set1
#  - set1a
#  - set1b
#  - set2
#  - set3
#  - set4
#  - set5
#  - set6

num_replicates: 1

jsit:
  patch_size: 32
  scale_factor: 3